### ISSUE TITLE
Unable to catch SocketException caused by lack of internet

### ISSUE THREAD

**Issue by LucasCLuk** [draw-dev/DRAW#112]
Ive been at this for a few hours trying to figure it out and I'm stuck. 

I've currently only tested this with ``Reddit.createUntrustedReadOnlyInstance`` so I'm not sure of other methods.

doing:
```dart
  try {
    var reddit = await Reddit.createUntrustedReadOnlyInstance(
        userAgent: userAgent, deviceId: "121212121212", clientId: clientId);
  } catch (e) {
    print(e);
  }
``` 
still spams the console
and even not using await and doing ``onError`` or ``.catchError`` still bubbles up to the console.

```dart
E/flutter (27985): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (27985): SocketException: Failed host lookup: 'www.reddit.com' (OS Error: No address associated with hostname, errno = 7)
E/flutter (27985): #0      IOClient.send (package:http/src/io_client.dart:30:23)
E/flutter (27985): <asynchronous suspension>
E/flutter (27985): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171:38)
E/flutter (27985): <asynchronous suspension>
E/flutter (27985): #2      BaseClient.post (package:http/src/base_client.dart:56:5)
E/flutter (27985): #3      Authenticator._requestTokenUntrusted (package:draw/src/auth.dart:283:39)
E/flutter (27985): <asynchronous suspension>
E/flutter (27985): #4      ReadOnlyAuthenticator._authenticationFlow (package:draw/src/auth.dart:400:13)
E/flutter (27985): <asynchronous suspension>
E/flutter (27985): #5      ReadOnlyAuthenticator.createUntrusted (package:draw/src/auth.dart:386:25)
E/flutter (27985): <asynchronous suspension>
E/flutter (27985): #6      new Reddit._untrustedReadOnlyInstance (package:draw/src/reddit.dart:369:27)
E/flutter (27985): #7      Reddit.createUntrustedReadOnlyInstance (package:draw/src/reddit.dart:112:24)
E/flutter (27985): <asynchronous suspension>
E/flutter (27985): #8      main (file://<redacted>/lib/main.dart:32:31)
E/flutter (27985): <asynchronous suspension>
E/flutter (27985): #9      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (27985): #10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by bkonyi** [comment]
Should be resolved now. Will publish in 0.4.3. Thanks for filing this!
