### ISSUE TITLE
Type Cast Error in v. 1.0.0

### ISSUE THREAD

**Issue by JohannesMilke** [draw-dev/DRAW#192]
I receive the following issue within the `Reddit.createScriptInstance` method while using version 1.0.0 with NullSafety. Before I was using another version without Null Safety and everything worked fine for me.

**Error Message** 
`type '_InternalLinkedHashMap<String, String?>' is not a subtype of type 'Map<String, String>?' in type cast`

**My implementation**
``` 
await Reddit.createScriptInstance(
        clientId: clientId,
        clientSecret: secret,
        userAgent: 'ChangeMeClient/0.1 by Name',
        username: username,
        password: password,
      );
```

**Comment by bkonyi** [comment]
Thanks for the report! Can you please provide me with a stack trace?

**Comment by JohannesMilke** [comment]
Here is the stacktrace:

```
#0      Authenticator._requestToken (package:draw/src/auth.dart:243:26)
#1      ScriptAuthenticator._authenticationFlow (package:draw/src/auth.dart:345:11)
#2      ScriptAuthenticator.create (package:draw/src/auth.dart:331:25)
#3      new Reddit._scriptInstance (package:draw/src/reddit.dart:491:25)
#4      Reddit.createScriptInstance (package:draw/src/reddit.dart:243:27)
#5      RedditApi.init (package:upload/api/reddit_api.dart:12:28)
#6      main (package:upload/main.dart:38:15)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by JohannesMilke** [comment]
Any news for this?

**Comment by bkonyi** [comment]
Sorry for the delay on this one, was caught up with other work. For future reference, I'm always happy to accept PRs :-)
