### ISSUE TITLE
Can't get a submission comments

### ISSUE THREAD

**Issue by Ivaskuu** [draw-dev/DRAW#49]
This is my code:
  ```
void test() async
  {
    int timer = 4;

    var subreddit = reddit.subreddit('python').hot();
    await for(UserContent submission in subreddit)
    {
      if(timer > 0)
      {
        Submission s = submission;

        if(!s.stickied)
        {
          print('Submission id: ' + s.id);
          print('Title: ' + s.title);
          print('Num upvotes: ' + s.upvotes.toString());
          print('Num comments: ' + s.numComments.toString());

          List<Comment> comments = s.comments.comments;
          for (var comment in comments)
          {
            print(comment.body);
          }

          timer--;
        }
      }
      else break;
    }
  }
```
And this is the error:
```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 4659): NoSuchMethodError: The getter 'comments' was called on null.
E/flutter ( 4659): Receiver: null
E/flutter ( 4659): Tried calling: comments
E/flutter ( 4659): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
E/flutter ( 4659): #1      ApiReddit.test (/data/user/0/com.skuu.focusreddit/cache/focus_redditQGUIDF/focus_reddit/lib/misc/api_reddit.dart:80:47)
E/flutter ( 4659): <asynchronous suspension>
E/flutter ( 4659): #2      ApiReddit.authorizeUser (/data/user/0/com.skuu.focusreddit/cache/focus_redditQGUIDF/focus_reddit/lib/misc/api_reddit.dart:36:7)
E/flutter ( 4659): <asynchronous suspension>
E/flutter ( 4659): #3      _LoginPageState.initState.<anonymous closure> (/data/user/0/com.skuu.focusreddit/cache/focus_redditQGUIDF/focus_reddit/lib/pages/login_page.dart:4
1:19)
E/flutter ( 4659): #4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
E/flutter ( 4659): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
E/flutter ( 4659): #6      _DelayedData.perform (dart:async/stream_impl.dart:578)
E/flutter ( 4659): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
E/flutter ( 4659): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
E/flutter ( 4659): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter ( 4659): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

Where `ApiReddit.test (/data/user/0/com.skuu.focusreddit/cache/focus_redditQGUIDF/focus_reddit/lib/misc/api_reddit.dart:80:47)` is `List<Comment> comments = s.comments.comments;`.

Am I doing something wrong?

**Comment by bkonyi** [comment]
If I'm not mistaken, the issue is you're trying to get the property
`comments` from a `List<Comment>`. Should probably only be `s.comments`

**Comment by Ivaskuu** [comment]
@bkonyi s.comments actually returns a CommentForest object..?

**Comment by bkonyi** [comment]
Ah sorry about that, clearly I didn't read my own documentation (wasn't at my desk). Yeah, this looks like a bug with how we create `Submission` objects in certain cases. A temporary workaround for this is to change this line:

```dart
Submission s = submission;
```

to this:

```dart
Submission s = await (submission as Submission).populate();
```

Unfortunately, this is an extra network request but I'll have to look into whether or not we can get around that. Also, keep in mind, `comments` can also return `MoreComments` so you'll have to check for that case in your comment loop.
