### ISSUE TITLE
How to get the user frontpage ?

### ISSUE THREAD

**Issue by Ivaskuu** [draw-dev/DRAW#53]
Hi.
I am trying to get the user frontpage. With **PRAW**, after a little search on the Praw docs I've found out that the command is `reddit.front.hot()`, but Draw doesn't seem to have the front property for the Reddit object.
I have tried:
```
Redditor rdt = await reddit.user.me();
await for(UserContent submission in rdt.hot())
  {
    Submission s = await (submission as Submission).populate();

    print(s.body);
    print(s.selftext);
    print(s.url);
}
```
but this gives an error when calling ` rdt.hot()` at line 76:
```
E/flutter ( 8691): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 8691): DRAWAuthenticationError: Status Code: 403 Reason: Forbidden
E/flutter ( 8691): #0      Authenticator._throwAuthenticationError (package:draw/src/auth.dart:240:5)
E/flutter ( 8691): #1      Authenticator._request (package:draw/src/auth.dart:194:7)
E/flutter ( 8691): <asynchronous suspension>
E/flutter ( 8691): #2      Authenticator.get (package:draw/src/auth.dart:125:12)
E/flutter ( 8691): <asynchronous suspension>
E/flutter ( 8691): #3      Reddit.get (package:draw/src/reddit.dart:301:33)
E/flutter ( 8691): <asynchronous suspension>
E/flutter ( 8691): #4      ListingGenerator.generator._nextBatch (package:draw/src/listing/listing_generator
.dart:49:38)
E/flutter ( 8691): <asynchronous suspension>
E/flutter ( 8691): #5      ListingGenerator.generator (package:draw/src/listing/listing_generator.dart:65:35
)
E/flutter ( 8691): <asynchronous suspension>
E/flutter ( 8691): #6      RedditBase&BaseListingMixin._buildGenerator (package:draw/src/listing/mixins/base
.dart:88:31)
E/flutter ( 8691): #7      RedditBase&BaseListingMixin.hot (package:draw/src/listing/mixins/base.dart:112:44
)
E/flutter ( 8691): #8      RedditApi.getUserFeed (/data/user/0/com.skuu.focusreddit/cache/focus_redditJDCDWH
/focus_reddit/lib/misc/reddit_api.dart:76:20)
E/flutter ( 8691): <asynchronous suspension>
E/flutter ( 8691): #9      _FeedPageState.initState (/data/user/0/com.skuu.focusreddit/cache/focus_redditJDC
DWH/focus_reddit/lib/pages/feed_page/feed_page.dart:40:15)
E/flutter ( 8691): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734:58)
E/flutter ( 8691): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 8691): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 8691): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 8691): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:
16)
E/flutter ( 8691): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter ( 8691): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
E/flutter ( 8691): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 8691): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 8691): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 8691): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:
16)
E/flutter ( 8691): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter ( 8691): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
E/flutter ( 8691): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 8691): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 8691): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 8691): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
E/flutter ( 8691): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 8691): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 8691): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
E/flutter ( 8691): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 8691): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 8691): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
E/flutter ( 8691): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 8691): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 8691): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter ( 8691): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter ( 8691): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
E/flutter ( 8691): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:22)
E/flutter ( 8691): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 8691): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter ( 8691): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter ( 8691): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter ( 8691): #43     Element
```
Whereas `reddit.subreddit('python').hot()`, for example, works with no problems. I can confirm that I am logged in, and that I can get my name or karma.

**Comment by bkonyi** [comment]
I've released 0.1.6 with this functionality. Thanks for the reports and your patience @Ivaskuu! It's a big help.
