### ISSUE TITLE
Some errors with variables types with Dart 2

### ISSUE THREAD

**Issue by Ivaskuu** [draw-dev/DRAW#74]
I've updated Flutter to the new recent beta, and there seems to be some erorrs...

```
E/flutter ( 5496): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 5496): type 'Future<dynamic>' is not a subtype of type 'FutureOr<Redditor>' where
E/flutter ( 5496):   Future is from dart:async
E/flutter ( 5496):   FutureOr is from dart:async
E/flutter ( 5496):   Redditor is from package:draw/src/models/redditor.dart
E/flutter ( 5496):
E/flutter ( 5496): #0      User.me (package:draw/src/user.dart:51:19)
E/flutter ( 5496): <asynchronous suspension>
E/flutter ( 5496): #1      RedditApi.updateUserInfos (file:///C:/Users/Adrian/Documents/MyApps/focus_reddit/lib/misc/reddit_api.dart:68:28)
```

My code calls `Redditor me = await reddit.user.me();` 

And here another one
```
E/flutter ( 5496): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 5496): type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' where
E/flutter ( 5496):   _InternalLinkedHashMap is from dart:collection
E/flutter ( 5496):   Map is from dart:core
E/flutter ( 5496):   String is from dart:core
E/flutter ( 5496):
E/flutter ( 5496): #0      Authenticator._request (package:draw/src/auth.dart:166:53)
E/flutter ( 5496): <asynchronous suspension>
E/flutter ( 5496): #1      Authenticator.get (package:draw/src/auth.dart:125:12)
E/flutter ( 5496): <asynchronous suspension>
E/flutter ( 5496): #2      Reddit.get (package:draw/src/reddit.dart:334:33)
E/flutter ( 5496): <asynchronous suspension>
E/flutter ( 5496): #3      ListingGenerator.generator._nextBatch (package:draw/src/listing/listing_generator.dart:49:38)
E/flutter ( 5496): <asynchronous suspension>
E/flutter ( 5496): #4      ListingGenerator.generator (package:draw/src/listing/listing_generator.dart:65:35)
E/flutter ( 5496): <asynchronous suspension>
E/flutter ( 5496): #5      _FrontPage&RedditBase&BaseListingMixin._buildGenerator (package:draw/src/listing/mixins/base.dart:91:29)
E/flutter ( 5496): #6      _FrontPage&RedditBase&BaseListingMixin.hot (package:draw/src/listing/mixins/base.dart:112:44)
E/flutter ( 5496): #7      PostsLoader._loadUserFeed (file:///C:/Users/Adrian/Documents/MyApps/focus_reddit/lib/misc/posts_loader.dart:34:66)
E/flutter ( 5496): <asynchronous suspension>
E/flutter ( 5496): #8      new PostsLoader (file:///C:/Users/Adrian/Documents/MyApps/focus_reddit/lib/misc/posts_loader.dart:21:5)
E/flutter ( 5496): #9      FeedPageState.initState (file:///C:/Users/Adrian/Documents/MyApps/focus_reddit/lib/pages/feed_page/feed_page.dart:76:28)
E/flutter ( 5496): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3743:58)
E/flutter ( 5496): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter ( 5496): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter ( 5496): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter ( 5496): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
E/flutter ( 5496): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter ( 5496): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter ( 5496): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
E/flutter ( 5496): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
E/flutter ( 5496): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
E/flutter ( 5496): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter ( 5496): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter ( 5496): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter ( 5496): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
E/flutter ( 5496): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter ( 5496): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter ( 5496): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
E/flutter ( 5496): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter ( 5496): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter ( 5496): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
E/flutter ( 5496): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter ( 5496): #31     Element.updateChild (package:flutter/src/widgets/
etc
```

My code is calling 
`RedditApi.reddit.front.hot();`

**Comment by bkonyi** [comment]
Looks like there needs to be some relatively involved changes to make the Dart 2 type system happy. In the meantime, pass `--no-preview-dart-2` to `flutter`. Unfortunately, this will prevent you from using Dart 2 features like optional `new` and `const`, but hopefully this won't take more than a few days to resolve.
